version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_ROOT: "http://localhost:8000"
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_ROOT=http://localhost:8000
